//! ACELP / LPD ROM tables for MPEG-D USAC's speech-coding mode.
//!
//! Generated by `tools/extract_acelp_rom.py` directly from the C reference --
//! do not hand-edit, re-run the script instead (porting rule R4 in
//! text/plan.txt). Sources: `ixheaacd_rom.c`, `ixheaacd_avq_rom.c` and
//! `ixheaacd_acelp_tools.c` in `c/libxaac/decoder/`.

/// LPC order every LPD frame uses (`ORDER` in `ixheaacd_cnst.h`).
pub const ORDER: usize = 16;
/// Samples in one ACELP subframe (`LEN_SUBFR`).
pub const LEN_SUBFR: usize = 64;
/// Sub-sample resolution of the adaptive-codebook pitch lag (`UP_SAMP`).
pub const UP_SAMP: usize = 4;
/// Taps either side of centre in the fractional-pitch interpolator
/// (`INTER_LP_FIL_ORDER`).
pub const INTER_LP_FIL_ORDER: usize = 16;
/// Pre-emphasis / de-emphasis factor (`PREEMPH_FILT_FAC`).
pub const PREEMPH_FILT_FAC: f32 = 0.68;
/// Spectral tilt applied to the innovation before gain search (`TILT_CODE`).
pub const TILT_CODE: f32 = 0.3;
/// Pitch-sharpening weight (`F_PIT_SHARP` in `ixheaacd_acelp_decode.c`).
pub const F_PIT_SHARP: f32 = 0.85;
/// Narrowest and widest pitch lags, and the two fractional-resolution
/// breakpoints, before the sampling-rate scaling `i_offset` shifts them
/// (`TMIN`, `TFR2`, `TFR1`, `TMAX`).
pub const TMIN: i32 = 34;
pub const TFR2: i32 = 162 - TMIN;
pub const TFR1: i32 = 160;
pub const TMAX: i32 = 27 + 6 * TMIN;
/// Denominator of the `fscale` pitch-range scaling (`FSCALE_DENOM`).
pub const FSCALE_DENOM: i32 = 12800;

/// The gain VQ codebook (`ixheaacd_int_leave_gain_table`), interleaved as 128
/// (pitch gain, innovation gain) pairs: entry `2*i` is the adaptive-codebook
/// gain applied directly, entry `2*i+1` scales the energy-predicted innovation
/// gain rather than being used as a gain itself.
#[rustfmt::skip]
pub const GAIN_TABLE: [f32; 256] = [
    0.012445, 0.215546, 0.028326, 0.965442, 0.053042, 0.525819,
    0.065409, 1.495322, 0.078212, 2.323725, 0.100504, 0.751276,
    0.112617, 3.42753, 0.113124, 0.309583, 0.121763, 1.140685,
    0.143515, 7.519609, 0.16243, 0.568752, 0.16494, 1.904113,
    0.165429, 4.947562, 0.194985, 0.855463, 0.213527, 1.281019,
    0.223544, 0.414672, 0.243135, 2.781766, 0.25718, 1.659565,
    0.269488, 0.636749, 0.286539, 1.003938, 0.328124, 2.225436,
    0.328761, 0.330278, 0.336807, 11.500983, 0.339794, 3.805726,
    0.344454, 1.494626, 0.346165, 0.738748, 0.363605, 1.141454,
    0.398729, 0.517614, 0.415276, 2.928666, 0.416282, 0.862935,
    0.423421, 1.87331, 0.444151, 0.202244, 0.445842, 1.301113,
    0.455671, 5.519512, 0.484764, 0.387607, 0.488696, 0.967884,
    0.48873, 0.666771, 0.508189, 1.516224, 0.508792, 2.348662,
    0.531504, 3.88387, 0.548649, 1.112861, 0.551182, 0.514986,
    0.564397, 1.74203, 0.566598, 0.796454, 0.589255, 3.081743,
    0.598816, 1.271936, 0.617654, 0.333501, 0.619073, 2.040522,
    0.625282, 0.950244, 0.630798, 0.594883, 0.638918, 4.863197,
    0.650102, 1.464846, 0.668412, 0.747138, 0.66949, 2.583027,
    0.683757, 1.125479, 0.691216, 1.739274, 0.718441, 3.297789,
    0.722608, 0.902743, 0.728827, 2.194941, 0.729586, 0.633849,
    0.730907, 7.432957, 0.731017, 0.431076, 0.731543, 1.387847,
    0.759183, 1.04521, 0.768606, 1.789648, 0.771245, 4.085637,
    0.772613, 0.778145, 0.786483, 1.283204, 0.792467, 2.412891,
    0.802393, 0.544588, 0.807156, 0.255978, 0.81428, 1.544409,
    0.817839, 0.938798, 0.826959, 2.910633, 0.830453, 0.684066,
    0.833431, 1.171532, 0.841208, 1.908628, 0.84644, 5.333522,
    0.86828, 0.841519, 0.868662, 1.43523, 0.871449, 3.675784,
    0.881317, 2.245058, 0.88202, 0.480249, 0.882476, 1.105804,
    0.902856, 0.68485, 0.904419, 1.682113, 0.909384, 2.787801,
    0.916558, 7.500981, 0.918444, 0.950341, 0.919721, 1.296319,
    0.940272, 4.682978, 0.940273, 1.991736, 0.950291, 3.507281,
    0.957455, 1.116284, 0.957723, 0.793034, 0.958217, 1.497824,
    0.962628, 2.514156, 0.968507, 0.588605, 0.974739, 0.339933,
    0.991738, 1.750201, 0.99721, 0.936131, 1.002422, 1.250008,
    1.00604, 2.167232, 1.008848, 3.12994, 1.014404, 5.842819,
    1.027798, 4.287319, 1.039404, 1.489295, 1.039628, 8.947958,
    1.043214, 0.765733, 1.045089, 2.537806, 1.058994, 1.031496,
    1.060415, 0.478612, 1.072132, 12.8, 1.074778, 1.910049,
    1.07657, 15.9999, 1.107853, 3.843067, 1.110673, 1.228576,
    1.110969, 2.758471, 1.140058, 1.603077, 1.155384, 0.668935,
    1.176229, 6.717108, 1.179008, 2.01194, 1.187735, 0.963552,
    1.199569, 4.891432, 1.206311, 3.316329, 1.215323, 2.507536,
    1.22315, 1.387102, 1.296012, 9.684225,
];

/// The 4x-oversampled FIR used to evaluate the adaptive codebook at fractional
/// pitch lags (`ixheaacd_interpol_filt`): `UP_SAMP * INTER_LP_FIL_ORDER + 1`
/// taps, read at stride `UP_SAMP` from two phase offsets per output sample.
#[rustfmt::skip]
pub const INTERPOL_FILT: [f32; 65] = [
    0.94, 0.85639, 0.632268, 0.33756, 0.059072, -0.131059,
    -0.199393, -0.158569, -0.056359, 0.047606, 0.106749, 0.103705,
    0.052062, -0.015182, -0.063705, -0.07366, -0.046497, -0.000983,
    0.038227, 0.053143, 0.040059, 0.009308, -0.021674, -0.037767,
    -0.033186, -0.013028, 0.010702, 0.025901, 0.026318, 0.013821,
    -0.003645, -0.016813, -0.019855, -0.012766, -0.00053, 0.01008,
    0.014122, 0.010657, 0.002594, -0.005363, -0.009344, -0.008101,
    -0.003182, 0.00233, 0.005635, 0.005562, 0.002844, -0.000627,
    -0.002993, -0.003362, -0.002044, -0.000116, 0.001315, 0.001692,
    0.001151, 0.000259, -0.000417, -0.000618, -0.000434, -0.000133,
    6.3e-05, 9.8e-05, 4.8e-05, 7e-06, 0.0,
];

/// Low-pass FIR of the bass post-filter (`ixheaacd_fir_lp_filt`), one side of a
/// symmetric `2*FILTER_DELAY + 1` kernel.
#[rustfmt::skip]
pub const FIR_LP_FILT: [f32; 13] = [
    0.08825, 0.08641, 0.081074, 0.072768, 0.062294, 0.050623,
    0.038774, 0.027692, 0.01813, 0.010578, 0.005221, 0.001946,
    0.000385,
];

/// Powers of the bandwidth-expansion factor 0.92 (`ixheaacd_gamma_table`),
/// `gamma[j] = 0.92^j`, used to weight LPC coefficients for the weighted
/// synthesis filter that shapes FAC.
#[rustfmt::skip]
pub const GAMMA_TABLE: [f32; 17] = [
    1.0, 0.92, 0.8464, 0.778688, 0.716393, 0.659082,
    0.606355, 0.557847, 0.513219, 0.472161, 0.434389, 0.399637,
    0.367666, 0.338253, 0.311193, 0.286298, 0.263394,
];

