"""Extract scalefactor-band and TNS ROM tables from the reference C implementation."""
import re, sys

ROM = "c/libxaac/decoder/ixheaacd_aac_rom.c"
lines = open(ROM).read().split("\n")
marks = [(i, l.strip()) for i, l in enumerate(lines) if l.strip().startswith("//")]

def nums_after(start, count, stop_on_neg1=False):
    out, i = [], start + 1
    while i < len(lines) and (len(out) < count if count else True):
        ln = re.sub(r"/\*.*?\*/", " ", lines[i])
        ln = re.sub(r"//.*", "", ln)
        for tok in re.findall(r"-?0[xX][0-9a-fA-F]+|-?\d+", ln):
            v = int(tok, 0)
            if stop_on_neg1 and v == -1:
                return out
            out.append(v)
            if count and len(out) == count:
                break
        i += 1
    return out

def find(marker):
    for (n, t) in marks:
        if marker in t:
            return n
    print("MISSING:", marker, file=sys.stderr); sys.exit(1)

# SFB tables: (comment marker, rust name) - terminated by -1 in the C source
SFB = [
    ("ixheaacd_sfb_96_1024[42]", "SFB_96_1024"),
    ("ixheaacd_sfb_96_128[13]",  "SFB_96_128"),
    ("ixheaacd_sfb_64_1024[48]", "SFB_64_1024"),
    ("ixheaacd_sfb_48_1024[50]", "SFB_48_1024"),
    ("ixheaacd_sfb_48_128[15]",  "SFB_48_128"),
    ("ixheaacd_sfb_32_1024[52]", "SFB_32_1024"),
    ("ixheaacd_sfb_24_1024[48]", "SFB_24_1024"),
    ("ixheaacd_sfb_24_128[16]",  "SFB_24_128"),
    ("ixheaacd_sfb_16_1024[44]", "SFB_16_1024"),
    ("ixheaacd_sfb_16_128[16]",  "SFB_16_128"),
    ("ixheaacd_sfb_8_1024[41]",  "SFB_8_1024"),
    ("ixheaacd_sfb_8_128[16]",   "SFB_8_128"),
    ("ixheaacd_sfb_48_512[37]",  "SFB_48_512"),
    ("ixheaacd_sfb_32_512[38]",  "SFB_32_512"),
    ("ixheaacd_sfb_24_512[32]",  "SFB_24_512"),
    ("ixheaacd_sfb_48_480[36]",  "SFB_48_480"),
    ("ixheaacd_sfb_32_480[38]",  "SFB_32_480"),
    ("ixheaacd_sfb_24_480[31]",  "SFB_24_480"),
    ("sfb_96_960[41]",  "SFB_96_960"),
    ("sfb_96_120[13]",  "SFB_96_120"),
    ("sfb_64_960[47]",  "SFB_64_960"),
    ("sfb_48_960[50]",  "SFB_48_960"),
    ("sfb_48_120[15]",  "SFB_48_120"),
    ("sfb_24_960[47]",  "SFB_24_960"),
    ("sfb_24_120[16]",  "SFB_24_120"),
    ("sfb_16_960[43]",  "SFB_16_960"),
    ("sfb_16_120[16]",  "SFB_16_120"),
    ("sfb_8_960[41]",   "SFB_8_960"),
    ("sfb_8_120[16]",   "SFB_8_120"),
]

out = ["//! Scalefactor-band width tables ported verbatim from the reference C\n"
       "//! implementation (`c/libxaac/decoder/ixheaacd_aac_rom.c`).\n//!\n"
       "//! Generated by tools/extract_sfb.py - do not edit by hand.\n"]

for marker, name in SFB:
    vals = nums_after(find(marker), 0, stop_on_neg1=True)
    total = sum(vals)
    out.append("/// %d bands, %d spectral lines total.\npub static %s: &[u8] = &[%s];\n"
               % (len(vals), total, name, ", ".join(str(v) for v in vals)))

# TNS max bands: 12 rows x 2 cols
tns = nums_after(find("tns_max_bands_tbl[12][2]"), 24)
rows = ", ".join("[%d, %d]" % (tns[2*i], tns[2*i+1]) for i in range(12))
out.append("/// Max TNS bands per sample-rate index: `[long, short]`.\n"
           "pub static TNS_MAX_BANDS: [[u8; 2]; 12] = [%s];\n" % rows)

tns_ld = nums_after(find("tns_max_bands_tbl_ld[12]"), 12)
if len(tns_ld) == 12:
    out.append("/// Max TNS bands for AAC-LD per sample-rate index.\n"
               "pub static TNS_MAX_BANDS_LD: [u8; 12] = [%s];\n" % ", ".join(map(str, tns_ld)))

open("src/tables/sfb.rs", "w").write("\n".join(out))
print("wrote src/tables/sfb.rs")
for marker, name in SFB:
    vals = nums_after(find(marker), 0, stop_on_neg1=True)
    print("  %-14s bands=%3d total=%5d" % (name, len(vals), sum(vals)))
