#!/usr/bin/env python3
"""Extract the ACELP/LPD float ROM tables from libxaac into src/tables/usac_acelp.rs.

Porting rule R4 in text/plan.txt: tables are generated from the C source, never
retyped, so a reference update is a re-run rather than a diff review. Run from
the repo root:

    python3 tools/extract_acelp_rom.py > src/tables/usac_acelp.rs
"""
import re, sys

C = 'c/libxaac/'
SPEC = [
    ('decoder/ixheaacd_rom.c',        'ixheaacd_int_leave_gain_table', 256, 'GAIN_TABLE'),
    ('decoder/ixheaacd_avq_rom.c',    'ixheaacd_interpol_filt',         65, 'INTERPOL_FILT'),
    ('decoder/ixheaacd_avq_rom.c',    'ixheaacd_fir_lp_filt',           13, 'FIR_LP_FILT'),
    ('decoder/ixheaacd_acelp_tools.c','ixheaacd_gamma_table',           17, 'GAMMA_TABLE'),
]

def grab(path, name, count):
    src = open(C + path, errors='ignore').read()
    m = re.search(r'\b' + re.escape(name) + r'\s*\[[^\]]*\]\s*=\s*\{', src)
    if not m:
        sys.exit('not found: %s in %s' % (name, path))
    i = m.end(); depth = 1; out = []
    while depth:
        ch = src[i]
        if ch == '{': depth += 1
        elif ch == '}':
            depth -= 1
            if not depth: break
        out.append(ch); i += 1
    body = ''.join(out)
    vals = [v.strip().rstrip('fF') for v in body.split(',') if v.strip()]
    if len(vals) != count:
        sys.exit('%s: expected %d values, got %d' % (name, count, len(vals)))
    return [float(v) for v in vals]

def emit(name, vals, per_line, doc):
    print(doc)
    print('#[rustfmt::skip]')
    print('pub const %s: [f32; %d] = [' % (name, len(vals)))
    for i in range(0, len(vals), per_line):
        row = ', '.join('%r' % v for v in vals[i:i + per_line])
        print('    %s,' % row)
    print('];')
    print()

tables = {n: grab(p, c, k) for p, c, k, n in SPEC}

print('''//! ACELP / LPD ROM tables for MPEG-D USAC's speech-coding mode.
//!
//! Generated by `tools/extract_acelp_rom.py` directly from the C reference --
//! do not hand-edit, re-run the script instead (porting rule R4 in
//! text/plan.txt). Sources: `ixheaacd_rom.c`, `ixheaacd_avq_rom.c` and
//! `ixheaacd_acelp_tools.c` in `c/libxaac/decoder/`.

/// LPC order every LPD frame uses (`ORDER` in `ixheaacd_cnst.h`).
pub const ORDER: usize = 16;
/// Samples in one ACELP subframe (`LEN_SUBFR`).
pub const LEN_SUBFR: usize = 64;
/// Sub-sample resolution of the adaptive-codebook pitch lag (`UP_SAMP`).
pub const UP_SAMP: usize = 4;
/// Taps either side of centre in the fractional-pitch interpolator
/// (`INTER_LP_FIL_ORDER`).
pub const INTER_LP_FIL_ORDER: usize = 16;
/// Pre-emphasis / de-emphasis factor (`PREEMPH_FILT_FAC`).
pub const PREEMPH_FILT_FAC: f32 = 0.68;
/// Spectral tilt applied to the innovation before gain search (`TILT_CODE`).
pub const TILT_CODE: f32 = 0.3;
/// Pitch-sharpening weight (`F_PIT_SHARP` in `ixheaacd_acelp_decode.c`).
pub const F_PIT_SHARP: f32 = 0.85;
/// Narrowest and widest pitch lags, and the two fractional-resolution
/// breakpoints, before the sampling-rate scaling `i_offset` shifts them
/// (`TMIN`, `TFR2`, `TFR1`, `TMAX`).
pub const TMIN: i32 = 34;
pub const TFR2: i32 = 162 - TMIN;
pub const TFR1: i32 = 160;
pub const TMAX: i32 = 27 + 6 * TMIN;
/// Denominator of the `fscale` pitch-range scaling (`FSCALE_DENOM`).
pub const FSCALE_DENOM: i32 = 12800;
''')

emit('GAIN_TABLE', tables['GAIN_TABLE'], 6,
'''/// The gain VQ codebook (`ixheaacd_int_leave_gain_table`), interleaved as 128
/// (pitch gain, innovation gain) pairs: entry `2*i` is the adaptive-codebook
/// gain applied directly, entry `2*i+1` scales the energy-predicted innovation
/// gain rather than being used as a gain itself.''')
emit('INTERPOL_FILT', tables['INTERPOL_FILT'], 6,
'''/// The 4x-oversampled FIR used to evaluate the adaptive codebook at fractional
/// pitch lags (`ixheaacd_interpol_filt`): `UP_SAMP * INTER_LP_FIL_ORDER + 1`
/// taps, read at stride `UP_SAMP` from two phase offsets per output sample.''')
emit('FIR_LP_FILT', tables['FIR_LP_FILT'], 6,
'''/// Low-pass FIR of the bass post-filter (`ixheaacd_fir_lp_filt`), one side of a
/// symmetric `2*FILTER_DELAY + 1` kernel.''')
emit('GAMMA_TABLE', tables['GAMMA_TABLE'], 6,
'''/// Powers of the bandwidth-expansion factor 0.92 (`ixheaacd_gamma_table`),
/// `gamma[j] = 0.92^j`, used to weight LPC coefficients for the weighted
/// synthesis filter that shapes FAC.''')
