import re, sys

ROM = "/Users/alex/Documents/code/rust/aac/c/libxaac/decoder/ixheaacd_aac_rom.c"
src = open(ROM).read()
lines = src.split("\n")

# markers: (comment_substring, rust_name, count, type)
SPEC = [
    ("idx_hf11", "IDX_TABLE_HF11", 21, "u32"),
    ("idx_hf10", "IDX_TABLE_HF10", 20, "u32"),
    ("idx_hf9",  "IDX_TABLE_HF9",  23, "u32"),
    ("idx_hf8",  "IDX_TABLE_HF8",  17, "u32"),
    ("idx_hf7",  "IDX_TABLE_HF7",  18, "u32"),
    ("idx_hf6",  "IDX_TABLE_HF6",  17, "u32"),
    ("idx_hf5",  "IDX_TABLE_HF5",  19, "u32"),
    ("idx_hf4",  "IDX_TABLE_HF4",  19, "u32"),
    ("idx_hf3",  "IDX_TABLE_HF3",  27, "u32"),
    ("idx_hf2",  "IDX_TABLE_HF2",  16, "u32"),
    ("idx_hf1",  "IDX_TABLE_HF1",  12, "u32"),
    ("inp_hf11", "INPUT_TABLE_CB11", 290, "u16"),
    ("inp_hf10", "INPUT_TABLE_CB10", 170, "u16"),
    ("inp_hf9",  "INPUT_TABLE_CB9",  170, "u16"),
    ("inp_hf8",  "INPUT_TABLE_CB8",   65, "u16"),
    ("inp_hf7",  "INPUT_TABLE_CB7",   65, "u16"),
    ("inp_hf6",  "INPUT_TABLE_CB6",   82, "u16"),
    ("inp_hf5",  "INPUT_TABLE_CB5",   82, "u16"),
    ("inp_hf4",  "INPUT_TABLE_CB4",   82, "u16"),
    ("inp_hf3",  "INPUT_TABLE_CB3",   82, "u16"),
    ("inp_hf2",  "INPUT_TABLE_CB2",   82, "u16"),
    ("inp_hf1",  "INPUT_TABLE_CB1",   82, "u16"),
    ("UWORD16 huffman_code_book_scl[122];", "HUFFMAN_CODE_BOOK_SCL", 122, "u16"),
    ("UWORD32 huffman_code_book_scl_index[33];", "HUFFMAN_CODE_BOOK_SCL_INDEX", 33, "u32"),
]

# find marker line numbers
marks = []
for i, ln in enumerate(lines):
    s = ln.strip()
    if s.startswith("//"):
        marks.append((i, s))

def nums_after(start_line, count):
    """Collect `count` numeric literals starting after start_line, skipping comments."""
    out = []
    i = start_line + 1
    while i < len(lines) and len(out) < count:
        ln = lines[i]
        # strip // comments
        ln = re.sub(r"//.*", "", ln)
        for tok in re.findall(r"-?0[xX][0-9a-fA-F]+|-?\d+", ln):
            out.append(int(tok, 0))
            if len(out) == count:
                break
        i += 1
    return out

results = {}
for marker, name, count, ty in SPEC:
    idx = None
    for (ln_no, txt) in marks:
        body = txt.lstrip("/").strip()
        # Exact match on the comment body: a prefix match would let "inp_hf1"
        # bind to the "inp_hf11" table.
        if body == marker or body.endswith(" " + marker):
            idx = ln_no
            break
    if idx is None:
        print("MISSING MARKER:", marker, file=sys.stderr); sys.exit(1)
    vals = nums_after(idx, count)
    if len(vals) != count:
        print("SHORT:", name, len(vals), file=sys.stderr); sys.exit(1)
    results[name] = (vals, ty, count)

out = []
out.append("//! Huffman codebook ROM tables ported verbatim from the reference C\n"
           "//! implementation (`c/libxaac/decoder/ixheaacd_aac_rom.c`).\n//!\n"
           "//! Generated by tools/extract_rom.py - do not edit by hand.\n")
for marker, name, count, ty in SPEC:
    vals, ty, count = results[name]
    if ty == "u32":
        body = ", ".join("0x%08X" % (v & 0xFFFFFFFF) for v in vals)
    else:
        body = ", ".join("0x%04X" % (v & 0xFFFF) for v in vals)
    out.append("pub static %s: [%s; %d] = [%s];\n" % (name, ty, count, body))

open("/Users/alex/Documents/code/rust/aac/src/tables/huffman_rom.rs", "w").write("\n".join(out))
print("wrote", len(SPEC), "tables")
for marker, name, count, ty in SPEC:
    print("  %-30s %5d %s" % (name, count, ty))
